### PR TITLE
Add DNS cache.

### PR DESCRIPTION
**Pull request by irneh-pl**
I tested this fairly well.

### CODE REVIEW

**Comment by arktos65** [comment]
I'd like to see this recipe invoked as an optional setting.  You can do this by creating attributes/default.rb and add the attribute "default['server-base']['install_dnsmasq'] = true". 

Then in the recipes/default.rb, change "include_recipe 'server-base::dnsmasq'" to:

if node['server-base']['install_dnsmasq']
    include_recipe 'server-base::dnsmasq'
end

This will provide some flexibility (e.g. Vagrant boxes probably shouldn't use this recipe).

**Comment by irneh-pl** [comment]
Good idea. Solves the version-pinning problem. I'd be inclined to default it to false to be consistent with vanilla Ubuntu not having a DNS cache. Would we do:
````
node.override['server-base']['install_dnsmasq'] = true
```

**Comment by irneh-pl** [comment]
Were you planning to enhance it with your notes and
```
node.override['server-base']['install_dnsmasq'] = true
```
or shall I do that now?

**Comment by irneh-pl** [comment]
I'll do it now.

**Pull request merged**
